import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "es" | "en" | "fr" | "ko" | "pl" | "bg";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    "header.title": "Sysde",
    "header.subtitle": "Arrendamiento",
    "header.demo": "Agendar una Demo",
    "slide.inicio": "Inicio",
    "slide.flujo": "Flujo",
    "slide.reglas": "Reglas",
    "slide.riesgos": "Riesgos",
    "slide.comerciales": "Comerciales",
    "slide.formalizacion": "Formalización",
    "slide.activos": "Activos",
    "slide.reportes": "Reportes",
    "slide.cierre": "Cierre",
    // Map nodes
    "map.title": "Arrendamiento",
    "map.subtitle": "Mapa Funcional",
    "map.clients": "Líderes que confían en Sysde",
    "node.inicio": "Inicio",
    "node.flujo": "Flujo Operativo",
    "node.reglas": "Reglas",
    "node.riesgos": "Riesgos",
    "node.comerciales": "Comerciales",
    "node.formalizacion": "Formalización",
    "node.activos": "Admin. Activos",
    "node.reportes": "Reportes",
    "node.cierre": "Cierre",
    // Gate 0 - Contact
    "gate0.title": "Antes de comenzar...",
    "gate0.subtitle": "Cuéntanos sobre ti para personalizar la experiencia",
    "gate0.company": "Empresa",
    "gate0.company.placeholder": "Nombre de tu empresa",
    "gate0.email": "Correo electrónico",
    "gate0.email.placeholder": "tu@empresa.com",
    "gate0.whatsapp": "WhatsApp",
    "gate0.whatsapp.placeholder": "+52 55 1234 5678",
    "gate0.continue": "Continuar",
    // Gate forms
    "gate.yes": "Sí",
    "gate.no": "No",
    "gate1.title": "¿Tienen operación activa de leasing hoy?",
    "gate2.title": "Meta de originación mensual (6–12m):",
    "gate3.title": "¿Tienen sistema para administrar leasing?",
    "gate4.title": "Usuarios que operan leasing",
    "gate4.subtitle": "(usuarios internos que requieren acceso al sistema)",
    "gate4.title.prospect": "¿Cuántos usuarios planean tener?",
    "gate4.subtitle.prospect": "(usuarios internos que necesitarán acceso al sistema)",
    "gate5.title": "¿Tienen un número confiable de contratos activos?",
    "gate5.title.prospect": "¿Desean tener contratos de leasing?",
    "gate6.title": "Contratos activos:",
    "gate6.title.prospect": "Número aproximado de contratos que desean tener:",
    // Language
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  en: {
    "header.title": "Sysde",
    "header.subtitle": "Leasing",
    "header.demo": "Schedule a Demo",
    "slide.inicio": "Home",
    "slide.flujo": "Flow",
    "slide.reglas": "Rules",
    "slide.riesgos": "Risks",
    "slide.comerciales": "Commercial",
    "slide.formalizacion": "Formalization",
    "slide.activos": "Assets",
    "slide.reportes": "Reports",
    "slide.cierre": "Closing",
    "map.title": "Leasing",
    "map.subtitle": "Functional Map",
    "map.clients": "Leaders who trust Sysde",
    "node.inicio": "Home",
    "node.flujo": "Operative Flow",
    "node.reglas": "Rules",
    "node.riesgos": "Risks",
    "node.comerciales": "Commercial",
    "node.formalizacion": "Formalization",
    "node.activos": "Asset Mgmt.",
    "node.reportes": "Reports",
    "node.cierre": "Closing",
    "gate0.title": "Before we begin...",
    "gate0.subtitle": "Tell us about yourself to personalize the experience",
    "gate0.company": "Company",
    "gate0.company.placeholder": "Your company name",
    "gate0.email": "Email",
    "gate0.email.placeholder": "you@company.com",
    "gate0.whatsapp": "WhatsApp",
    "gate0.whatsapp.placeholder": "+1 555 123 4567",
    "gate0.continue": "Continue",
    "gate.yes": "Yes",
    "gate.no": "No",
    "gate1.title": "Do you have an active leasing operation today?",
    "gate2.title": "Monthly origination goal (6–12m):",
    "gate3.title": "Do you have a system to manage leasing?",
    "gate4.title": "Users operating leasing",
    "gate4.subtitle": "(internal users who need system access)",
    "gate4.title.prospect": "How many users do you plan to have?",
    "gate4.subtitle.prospect": "(internal users who will need system access)",
    "gate5.title": "Do you have a reliable count of active contracts?",
    "gate5.title.prospect": "Do you plan to have leasing contracts?",
    "gate6.title": "Active contracts:",
    "gate6.title.prospect": "Approximate number of contracts you plan to have:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  fr: {
    "header.title": "Sysde",
    "header.subtitle": "Crédit-bail",
    "header.demo": "Planifier une Démo",
    "slide.inicio": "Accueil",
    "slide.flujo": "Flux",
    "slide.reglas": "Règles",
    "slide.riesgos": "Risques",
    "slide.comerciales": "Commercial",
    "slide.formalizacion": "Formalisation",
    "slide.activos": "Actifs",
    "slide.reportes": "Rapports",
    "slide.cierre": "Clôture",
    "map.title": "Crédit-bail",
    "map.subtitle": "Carte Fonctionnelle",
    "map.clients": "Leaders qui font confiance à Sysde",
    "node.inicio": "Accueil",
    "node.flujo": "Flux Opérationnel",
    "node.reglas": "Règles",
    "node.riesgos": "Risques",
    "node.comerciales": "Commercial",
    "node.formalizacion": "Formalisation",
    "node.activos": "Gestion Actifs",
    "node.reportes": "Rapports",
    "node.cierre": "Clôture",
    "gate0.title": "Avant de commencer...",
    "gate0.subtitle": "Parlez-nous de vous pour personnaliser l'expérience",
    "gate0.company": "Entreprise",
    "gate0.company.placeholder": "Nom de votre entreprise",
    "gate0.email": "Email",
    "gate0.email.placeholder": "vous@entreprise.com",
    "gate0.whatsapp": "WhatsApp",
    "gate0.whatsapp.placeholder": "+33 6 12 34 56 78",
    "gate0.continue": "Continuer",
    "gate.yes": "Oui",
    "gate.no": "Non",
    "gate1.title": "Avez-vous une opération de leasing active aujourd'hui ?",
    "gate2.title": "Objectif d'origination mensuel (6–12m) :",
    "gate3.title": "Avez-vous un système pour gérer le leasing ?",
    "gate4.title": "Utilisateurs opérant le leasing",
    "gate4.subtitle": "(utilisateurs internes nécessitant un accès au système)",
    "gate4.title.prospect": "Combien d'utilisateurs prévoyez-vous ?",
    "gate4.subtitle.prospect": "(utilisateurs internes qui auront besoin d'un accès)",
    "gate5.title": "Avez-vous un nombre fiable de contrats actifs ?",
    "gate5.title.prospect": "Prévoyez-vous des contrats de leasing ?",
    "gate6.title": "Contrats actifs :",
    "gate6.title.prospect": "Nombre approximatif de contrats souhaités :",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  ko: {
    "header.title": "Sysde",
    "header.subtitle": "리스",
    "header.demo": "데모 예약",
    "slide.inicio": "홈",
    "slide.flujo": "흐름",
    "slide.reglas": "규칙",
    "slide.riesgos": "위험",
    "slide.comerciales": "상업",
    "slide.formalizacion": "공식화",
    "slide.activos": "자산",
    "slide.reportes": "보고서",
    "slide.cierre": "종료",
    "map.title": "리스",
    "map.subtitle": "기능 맵",
    "map.clients": "Sysde를 신뢰하는 리더들",
    "node.inicio": "홈",
    "node.flujo": "운영 흐름",
    "node.reglas": "규칙",
    "node.riesgos": "위험",
    "node.comerciales": "상업",
    "node.formalizacion": "공식화",
    "node.activos": "자산 관리",
    "node.reportes": "보고서",
    "node.cierre": "종료",
    "gate0.title": "시작하기 전에...",
    "gate0.subtitle": "경험을 맞춤화하기 위해 알려주세요",
    "gate0.company": "회사",
    "gate0.company.placeholder": "회사명",
    "gate0.email": "이메일",
    "gate0.email.placeholder": "you@company.com",
    "gate0.whatsapp": "WhatsApp",
    "gate0.whatsapp.placeholder": "+82 10 1234 5678",
    "gate0.continue": "계속하기",
    "gate.yes": "예",
    "gate.no": "아니오",
    "gate1.title": "현재 활성 리스 운영이 있습니까?",
    "gate2.title": "월간 원천 목표 (6–12개월):",
    "gate3.title": "리스를 관리하는 시스템이 있습니까?",
    "gate4.title": "리스를 운영하는 사용자",
    "gate4.subtitle": "(시스템 접근이 필요한 내부 사용자)",
    "gate4.title.prospect": "몇 명의 사용자를 계획하고 있습니까?",
    "gate4.subtitle.prospect": "(시스템 접근이 필요한 내부 사용자)",
    "gate5.title": "활성 계약 수에 대한 신뢰할 수 있는 숫자가 있습니까?",
    "gate5.title.prospect": "리스 계약을 계획하고 있습니까?",
    "gate6.title": "활성 계약:",
    "gate6.title.prospect": "원하는 대략적인 계약 수:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  pl: {
    "header.title": "Sysde",
    "header.subtitle": "Leasing",
    "header.demo": "Umów Demo",
    "slide.inicio": "Start",
    "slide.flujo": "Przepływ",
    "slide.reglas": "Reguły",
    "slide.riesgos": "Ryzyko",
    "slide.comerciales": "Handlowe",
    "slide.formalizacion": "Formalizacja",
    "slide.activos": "Aktywa",
    "slide.reportes": "Raporty",
    "slide.cierre": "Zamknięcie",
    "map.title": "Leasing",
    "map.subtitle": "Mapa Funkcjonalna",
    "map.clients": "Liderzy, którzy ufają Sysde",
    "node.inicio": "Start",
    "node.flujo": "Przepływ Operacyjny",
    "node.reglas": "Reguły",
    "node.riesgos": "Ryzyko",
    "node.comerciales": "Handlowe",
    "node.formalizacion": "Formalizacja",
    "node.activos": "Zarządzanie Aktywami",
    "node.reportes": "Raporty",
    "node.cierre": "Zamknięcie",
    "gate0.title": "Zanim zaczniemy...",
    "gate0.subtitle": "Opowiedz nam o sobie, aby spersonalizować doświadczenie",
    "gate0.company": "Firma",
    "gate0.company.placeholder": "Nazwa firmy",
    "gate0.email": "Email",
    "gate0.email.placeholder": "ty@firma.com",
    "gate0.whatsapp": "WhatsApp",
    "gate0.whatsapp.placeholder": "+48 123 456 789",
    "gate0.continue": "Kontynuuj",
    "gate.yes": "Tak",
    "gate.no": "Nie",
    "gate1.title": "Czy macie aktywną operację leasingową?",
    "gate2.title": "Cel miesięcznej origination (6–12m):",
    "gate3.title": "Czy macie system do zarządzania leasingiem?",
    "gate4.title": "Użytkownicy operujący leasingiem",
    "gate4.subtitle": "(użytkownicy wewnętrzni wymagający dostępu do systemu)",
    "gate4.title.prospect": "Ilu użytkowników planujecie mieć?",
    "gate4.subtitle.prospect": "(użytkownicy wewnętrzni, którzy będą potrzebować dostępu)",
    "gate5.title": "Czy macie wiarygodną liczbę aktywnych umów?",
    "gate5.title.prospect": "Czy planujecie umowy leasingowe?",
    "gate6.title": "Aktywne umowy:",
    "gate6.title.prospect": "Przybliżona liczba planowanych umów:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  bg: {
    "header.title": "Sysde",
    "header.subtitle": "Лизинг",
    "header.demo": "Заявка за Демо",
    "slide.inicio": "Начало",
    "slide.flujo": "Поток",
    "slide.reglas": "Правила",
    "slide.riesgos": "Рискове",
    "slide.comerciales": "Търговски",
    "slide.formalizacion": "Формализация",
    "slide.activos": "Активи",
    "slide.reportes": "Отчети",
    "slide.cierre": "Затваряне",
    "map.title": "Лизинг",
    "map.subtitle": "Функционална Карта",
    "map.clients": "Лидери, които се доверяват на Sysde",
    "node.inicio": "Начало",
    "node.flujo": "Оперативен Поток",
    "node.reglas": "Правила",
    "node.riesgos": "Рискове",
    "node.comerciales": "Търговски",
    "node.formalizacion": "Формализация",
    "node.activos": "Управление на Активи",
    "node.reportes": "Отчети",
    "node.cierre": "Затваряне",
    "gate0.title": "Преди да започнем...",
    "gate0.subtitle": "Разкажете ни за себе си, за да персонализираме опита",
    "gate0.company": "Компания",
    "gate0.company.placeholder": "Име на компанията",
    "gate0.email": "Имейл",
    "gate0.email.placeholder": "вие@компания.com",
    "gate0.whatsapp": "WhatsApp",
    "gate0.whatsapp.placeholder": "+359 88 123 4567",
    "gate0.continue": "Продължи",
    "gate.yes": "Да",
    "gate.no": "Не",
    "gate1.title": "Имате ли активна лизингова операция днес?",
    "gate2.title": "Месечна цел за оригинация (6–12м):",
    "gate3.title": "Имате ли система за управление на лизинг?",
    "gate4.title": "Потребители, работещи с лизинг",
    "gate4.subtitle": "(вътрешни потребители, нуждаещи се от достъп до системата)",
    "gate4.title.prospect": "Колко потребители планирате да имате?",
    "gate4.subtitle.prospect": "(вътрешни потребители, които ще имат нужда от достъп)",
    "gate5.title": "Имате ли надежден брой активни договори?",
    "gate5.title.prospect": "Планирате ли лизингови договори?",
    "gate6.title": "Активни договори:",
    "gate6.title.prospect": "Приблизителен брой желани договори:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations.es[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
