import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "es" | "en" | "fr" | "ko" | "pl" | "bg";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    "header.title": "Sysde",
    "header.subtitle": "Arrendamiento",
    "header.demo": "Agendar una Demo",
    "slide.inicio": "Inicio",
    "slide.flujo": "Flujo",
    "slide.reglas": "Reglas",
    "slide.riesgos": "Riesgos",
    "slide.comerciales": "Comerciales",
    "slide.formalizacion": "Formalización",
    "slide.activos": "Activos",
    "slide.reportes": "Reportes",
    "slide.cierre": "Cierre",
    // Map nodes
    "map.title": "Arrendamiento",
    "map.subtitle": "Mapa Funcional",
    "map.clients": "Líderes que confían en Sysde",
    "node.inicio": "Inicio",
    "node.flujo": "Flujo Operativo",
    "node.reglas": "Reglas",
    "node.riesgos": "Riesgos",
    "node.comerciales": "Comerciales",
    "node.formalizacion": "Formalización",
    "node.activos": "Admin. Activos",
    "node.reportes": "Reportes",
    "node.cierre": "Cierre",
    // Gate forms
    "gate.yes": "Sí",
    "gate.no": "No",
    "gate1.title": "¿Tienen operación activa de leasing hoy?",
    "gate2.title": "Meta de originación mensual (6–12m):",
    "gate3.title": "¿Tienen sistema para administrar leasing?",
    "gate4.title": "Usuarios que operan leasing",
    "gate4.subtitle": "(usuarios internos que requieren acceso al sistema)",
    "gate5.title": "¿Tienen un número confiable de contratos activos?",
    "gate6.title": "Contratos activos:",
    // Language
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  en: {
    "header.title": "Sysde",
    "header.subtitle": "Leasing",
    "header.demo": "Schedule a Demo",
    "slide.inicio": "Home",
    "slide.flujo": "Flow",
    "slide.reglas": "Rules",
    "slide.riesgos": "Risks",
    "slide.comerciales": "Commercial",
    "slide.formalizacion": "Formalization",
    "slide.activos": "Assets",
    "slide.reportes": "Reports",
    "slide.cierre": "Closing",
    "map.title": "Leasing",
    "map.subtitle": "Functional Map",
    "map.clients": "Leaders who trust Sysde",
    "node.inicio": "Home",
    "node.flujo": "Operative Flow",
    "node.reglas": "Rules",
    "node.riesgos": "Risks",
    "node.comerciales": "Commercial",
    "node.formalizacion": "Formalization",
    "node.activos": "Asset Mgmt.",
    "node.reportes": "Reports",
    "node.cierre": "Closing",
    "gate.yes": "Yes",
    "gate.no": "No",
    "gate1.title": "Do you have an active leasing operation today?",
    "gate2.title": "Monthly origination goal (6–12m):",
    "gate3.title": "Do you have a system to manage leasing?",
    "gate4.title": "Users operating leasing",
    "gate4.subtitle": "(internal users who need system access)",
    "gate5.title": "Do you have a reliable count of active contracts?",
    "gate6.title": "Active contracts:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  fr: {
    "header.title": "Sysde",
    "header.subtitle": "Crédit-bail",
    "header.demo": "Planifier une Démo",
    "slide.inicio": "Accueil",
    "slide.flujo": "Flux",
    "slide.reglas": "Règles",
    "slide.riesgos": "Risques",
    "slide.comerciales": "Commercial",
    "slide.formalizacion": "Formalisation",
    "slide.activos": "Actifs",
    "slide.reportes": "Rapports",
    "slide.cierre": "Clôture",
    "map.title": "Crédit-bail",
    "map.subtitle": "Carte Fonctionnelle",
    "map.clients": "Leaders qui font confiance à Sysde",
    "node.inicio": "Accueil",
    "node.flujo": "Flux Opérationnel",
    "node.reglas": "Règles",
    "node.riesgos": "Risques",
    "node.comerciales": "Commercial",
    "node.formalizacion": "Formalisation",
    "node.activos": "Gestion Actifs",
    "node.reportes": "Rapports",
    "node.cierre": "Clôture",
    "gate.yes": "Oui",
    "gate.no": "Non",
    "gate1.title": "Avez-vous une opération de leasing active aujourd'hui ?",
    "gate2.title": "Objectif d'origination mensuel (6–12m) :",
    "gate3.title": "Avez-vous un système pour gérer le leasing ?",
    "gate4.title": "Utilisateurs opérant le leasing",
    "gate4.subtitle": "(utilisateurs internes nécessitant un accès au système)",
    "gate5.title": "Avez-vous un nombre fiable de contrats actifs ?",
    "gate6.title": "Contrats actifs :",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  ko: {
    "header.title": "Sysde",
    "header.subtitle": "리스",
    "header.demo": "데모 예약",
    "slide.inicio": "홈",
    "slide.flujo": "흐름",
    "slide.reglas": "규칙",
    "slide.riesgos": "위험",
    "slide.comerciales": "상업",
    "slide.formalizacion": "공식화",
    "slide.activos": "자산",
    "slide.reportes": "보고서",
    "slide.cierre": "종료",
    "map.title": "리스",
    "map.subtitle": "기능 맵",
    "map.clients": "Sysde를 신뢰하는 리더들",
    "node.inicio": "홈",
    "node.flujo": "운영 흐름",
    "node.reglas": "규칙",
    "node.riesgos": "위험",
    "node.comerciales": "상업",
    "node.formalizacion": "공식화",
    "node.activos": "자산 관리",
    "node.reportes": "보고서",
    "node.cierre": "종료",
    "gate.yes": "예",
    "gate.no": "아니오",
    "gate1.title": "현재 활성 리스 운영이 있습니까?",
    "gate2.title": "월간 원천 목표 (6–12개월):",
    "gate3.title": "리스를 관리하는 시스템이 있습니까?",
    "gate4.title": "리스를 운영하는 사용자",
    "gate4.subtitle": "(시스템 접근이 필요한 내부 사용자)",
    "gate5.title": "활성 계약 수에 대한 신뢰할 수 있는 숫자가 있습니까?",
    "gate6.title": "활성 계약:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  pl: {
    "header.title": "Sysde",
    "header.subtitle": "Leasing",
    "header.demo": "Umów Demo",
    "slide.inicio": "Start",
    "slide.flujo": "Przepływ",
    "slide.reglas": "Reguły",
    "slide.riesgos": "Ryzyko",
    "slide.comerciales": "Handlowe",
    "slide.formalizacion": "Formalizacja",
    "slide.activos": "Aktywa",
    "slide.reportes": "Raporty",
    "slide.cierre": "Zamknięcie",
    "map.title": "Leasing",
    "map.subtitle": "Mapa Funkcjonalna",
    "map.clients": "Liderzy, którzy ufają Sysde",
    "node.inicio": "Start",
    "node.flujo": "Przepływ Operacyjny",
    "node.reglas": "Reguły",
    "node.riesgos": "Ryzyko",
    "node.comerciales": "Handlowe",
    "node.formalizacion": "Formalizacja",
    "node.activos": "Zarządzanie Aktywami",
    "node.reportes": "Raporty",
    "node.cierre": "Zamknięcie",
    "gate.yes": "Tak",
    "gate.no": "Nie",
    "gate1.title": "Czy macie aktywną operację leasingową?",
    "gate2.title": "Cel miesięcznej origination (6–12m):",
    "gate3.title": "Czy macie system do zarządzania leasingiem?",
    "gate4.title": "Użytkownicy operujący leasingiem",
    "gate4.subtitle": "(użytkownicy wewnętrzni wymagający dostępu do systemu)",
    "gate5.title": "Czy macie wiarygodną liczbę aktywnych umów?",
    "gate6.title": "Aktywne umowy:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
  bg: {
    "header.title": "Sysde",
    "header.subtitle": "Лизинг",
    "header.demo": "Заявка за Демо",
    "slide.inicio": "Начало",
    "slide.flujo": "Поток",
    "slide.reglas": "Правила",
    "slide.riesgos": "Рискове",
    "slide.comerciales": "Търговски",
    "slide.formalizacion": "Формализация",
    "slide.activos": "Активи",
    "slide.reportes": "Отчети",
    "slide.cierre": "Затваряне",
    "map.title": "Лизинг",
    "map.subtitle": "Функционална Карта",
    "map.clients": "Лидери, които се доверяват на Sysde",
    "node.inicio": "Начало",
    "node.flujo": "Оперативен Поток",
    "node.reglas": "Правила",
    "node.riesgos": "Рискове",
    "node.comerciales": "Търговски",
    "node.formalizacion": "Формализация",
    "node.activos": "Управление на Активи",
    "node.reportes": "Отчети",
    "node.cierre": "Затваряне",
    "gate.yes": "Да",
    "gate.no": "Не",
    "gate1.title": "Имате ли активна лизингова операция днес?",
    "gate2.title": "Месечна цел за оригинация (6–12м):",
    "gate3.title": "Имате ли система за управление на лизинг?",
    "gate4.title": "Потребители, работещи с лизинг",
    "gate4.subtitle": "(вътрешни потребители, нуждаещи се от достъп до системата)",
    "gate5.title": "Имате ли надежден брой активни договори?",
    "gate6.title": "Активни договори:",
    "lang.es": "Español",
    "lang.en": "English",
    "lang.fr": "Français",
    "lang.ko": "한국어",
    "lang.pl": "Polski",
    "lang.bg": "Български",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations.es[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
